### ISSUE TITLE
Error if sympy is not installed

### ISSUE THREAD

**Issue by davidrgmcb** [LLNL/SoRa#2]
Readme describes sympy as optional, program still runs but errors at the end returning this.

Traceback (most recent call last):
  File "../sora.py", line 16, in <module>
    main()
  File "/home/david/Desktop/sora/SoRa/sora/sora.py", line 256, in main
    logger.printPopulation(0, hof)
  File "/home/david/Desktop/sora/SoRa/sora/printLogger.py", line 91, in printPopulation
    import sympy
ImportError: No module named sympy

**Comment by leek2** [comment]
Resolved by davidrgmcb
