### ISSUE TITLE
Overflow encountered in Numpy 1.14.1

### ISSUE THREAD

**Issue by charlesll** [LLNL/SoRa#5]
Hi,

I tried to use SoRa after a fresh install in a virtualenv in Linux. Here is the setup of the virtual env:

- Python 2.7.15
- Numpy 1.14.3
- Sympy 1.1.1
- deap 1.2
- mpi4py 3.0.0.

When trying to run the two examples in the /test_sr/ folder, it raises errors related to an overflow in numpy. 

This problem is solved with using Numpy 1.9 to 1.13. 

Here is the error message obtained when using Numpy 1.14: 

```
Traceback (most recent call last):
  File "../sora.py", line 16, in <module>
    main()
  File "/home/charles/sora/SoRa/sora/sora.py", line 232, in main
    toolbox.algorithm(pop)
  File "/home/charles/sora/lib/python2.7/site-packages/deap/gp.py", line 1045, in harm
    record = stats.compile(population) if stats else {}
  File "/home/charles/sora/lib/python2.7/site-packages/deap/tools/support.py", line 237, in compile
    record[name] = stats.compile(data)
  File "/home/charles/sora/lib/python2.7/site-packages/deap/tools/support.py", line 208, in compile
    entry[key] = func(values)
  File "/home/charles/sora/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2957, in mean
    out=out, **kwargs)
  File "/home/charles/sora/lib/python2.7/site-packages/numpy/core/_methods.py", line 70, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
FloatingPointError: overflow encountered in reduce
```

**Comment by leek2** [comment]
OK, thanks for the report.  I don't see any obvious reason why 1.14 should be different than 1.13, but I'll look into it.

**Comment by charlesll** [comment]
Yes, I don't understand why. Could it be a regression in Numpy?

**Comment by leek2** [comment]
For some reason I can't catch exceptions from numpy 1.14 reduce.  Maybe numpy just didn't used to throw them?  In any case, I put in a workaround that seems to work fine, so it's good enough I guess. numpy 1.14 now works.
